import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, CircleDashed, Image, Music2, Video } from "lucide-react";
import { Link } from "react-router-dom";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CURRENT_PROJECT_KEY, fetchAudioCapabilities, finalizeProjectOutput, getMusicCapabilities, listProjects, listWorkflows, type AudioCapabilities, type MusicCapabilities, type ProjectState, type WorkflowManifest } from "@/lib/project-api";
import { toast } from "sonner";

export default function Generate() {
  const [projects, setProjects] = useState<ProjectState[]>([]); const [projectId, setProjectId] = useState(localStorage.getItem(CURRENT_PROJECT_KEY) || ""); const [workflows, setWorkflows] = useState<WorkflowManifest[]>([]); const [audio, setAudio] = useState<AudioCapabilities | null>(null); const [music, setMusic] = useState<MusicCapabilities | null>(null);
  useEffect(() => { Promise.all([listProjects(), listWorkflows(), fetchAudioCapabilities(), getMusicCapabilities()]).then(([p, w, a, m]) => { setProjects(p); setWorkflows(w); setAudio(a); setMusic(m); }).catch(() => undefined); }, []);
  const runnable = workflows.filter(w => w.supports_api_submission); const counts = useMemo(() => ({ image: runnable.filter(w => w.category === "image").length, video: runnable.filter(w => w.category === "video").length, audio: runnable.filter(w => w.category === "audio").length }), [runnable]);
  return <AppShell><div className="space-y-6"><div><Badge variant="outline">Phase 2–3 production queue</Badge><h2 className="mt-3 text-3xl font-semibold">Generate</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Review dependencies, then move to the fixed API-backed composer for images, local Minimax video, ACE-Step music, dialogue, and sound effects.</p></div>
    <Card className="rounded-3xl"><CardHeader><CardTitle>Project context</CardTitle></CardHeader><CardContent className="flex gap-3"><select aria-label="Project" className="h-10 w-full rounded-md border border-input bg-background px-3" value={projectId} onChange={e => { setProjectId(e.target.value); localStorage.setItem(CURRENT_PROJECT_KEY, e.target.value); }}><option value="">Select project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><Button disabled={!projectId} onClick={async () => { try { await finalizeProjectOutput(projectId); toast.success("Output manifest finalized"); } catch { toast.error("Could not finalize output"); } }}>Finalize output</Button></CardContent></Card>
    <div className="grid gap-4 md:grid-cols-3"><Readiness icon={Image} label="Runnable image workflows" value={counts.image} ready={counts.image > 0}/><Readiness icon={Video} label="Local video workflows" value={counts.video} ready={counts.video > 0}/><Readiness icon={Music2} label="ACE-Step music" value={music?.ace.status || "loading"} ready={music?.ace.status === "available"}/></div>
    <div className="grid gap-6 lg:grid-cols-2"><Card className="rounded-3xl"><CardHeader><CardTitle>Production sections</CardTitle><CardDescription>Each section keeps its own request and output provenance.</CardDescription></CardHeader><CardContent className="space-y-3"><Action href="/media" title="Images and local Minimax video" detail="Choose only runnable API-format workflows and provide accepted keyframes."/><Action href="/audio" title="Automatic mixed dialogue" detail="Use the saved automatic character map and timed ChatterBox."/><Action href="/music-sound" title="ACE-Step music and Control-Foley" detail="Generate music and sound effects through fixed adapters."/><Action href="/audio-reconstruct" title="Audio reconstruction" detail="Calibrate voices and record one highlighted part at a time."/></CardContent></Card><Card className="rounded-3xl"><CardHeader><CardTitle>Workflow contract</CardTitle><CardDescription>{runnable.length} runnable API workflows; UI exports remain catalog-only.</CardDescription></CardHeader><CardContent className="space-y-2">{runnable.slice(0, 10).map(w => <div className="flex items-center justify-between rounded-xl border p-3 text-sm" key={w.id}><span>{w.label}</span><Badge variant="outline">{w.category} · {w.output_type}</Badge></div>)}{audio && <p className="pt-2 text-xs text-muted-foreground">ComfyUI: {audio.comfyui_online ? "online" : "offline"}; voices: {audio.blocks.filter(b => b.id === "voice_library").length ? "catalogued" : "not loaded"}.</p>}</CardContent></Card></div>
  </div></AppShell>;
}
function Readiness({ icon: Icon, label, value, ready }: { icon: typeof Image; label: string; value: string | number; ready: boolean }) { return <Card className="rounded-3xl"><CardContent className="flex items-center gap-3 p-5"><Icon className="h-5 w-5 text-primary"/><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></div>{ready ? <CheckCircle2 className="ml-auto h-5 w-5 text-primary"/> : <CircleDashed className="ml-auto h-5 w-5 text-muted-foreground"/>}</CardContent></Card>; }
function Action({ href, title, detail }: { href: string; title: string; detail: string }) { return <Button asChild variant="outline" className="h-auto w-full justify-between rounded-2xl p-4 text-left"><Link to={href}><span><span className="block font-medium">{title}</span><span className="mt-1 block text-xs font-normal text-muted-foreground">{detail}</span></span><ArrowRight className="h-4 w-4"/></Link></Button>; }
