import { useState } from "react";
import { Image as ImageIcon, Loader2, Upload } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { analyzeImageDetailer, cancelVisionRun, createVisionRun, CURRENT_PROJECT_KEY, getVisionRun } from "@/lib/project-api";

export default function ImageDetailer() {
  const [file, setFile] = useState<File | null>(null); const [mode, setMode] = useState<"quick" | "balanced" | "deep">("balanced");
  const [result, setResult] = useState<any>(null); const [busy, setBusy] = useState(false); const [runId, setRunId] = useState<string | null>(null); const [progress, setProgress] = useState(0); const [stage, setStage] = useState("");
  const run = async () => { if (!file) return; setBusy(true); setProgress(5); try { const projectId = localStorage.getItem(CURRENT_PROJECT_KEY); if (!projectId) { setResult(await analyzeImageDetailer(file, mode)); setProgress(100); toast.success("Image detail analysis complete."); } else { const queued = await createVisionRun(projectId, file, mode); setRunId(queued.run_id); const poll = async () => { const current = await getVisionRun(queued.run_id); setProgress(current.progress || 0); setStage(current.stage || ""); if (current.status === "completed") { setResult(current.result); setBusy(false); toast.success("Image detail analysis complete."); } else if (current.status === "failed" || current.status === "cancelled") { setBusy(false); toast.error(current.error || "Image analysis did not complete"); } else { window.setTimeout(poll, 1200); } }; await poll(); } } catch (e) { setBusy(false); toast.error(e instanceof Error ? e.message : "Image analysis failed"); } };
  const cancel = async () => { if (!runId) return; await cancelVisionRun(runId).catch(() => undefined); setBusy(false); toast.info("Analysis cancelled"); };
  return <AppShell><div className="space-y-6"><div><Badge variant="outline">Visual Intelligence</Badge><h2 className="mt-3 text-3xl font-semibold">Image Detailer</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Qwen interprets the image while optional computer-vision signals provide measurable evidence for characters, objects, camera, lighting and continuity.</p></div>
    <Card><CardHeader><CardTitle>Analyze an image</CardTitle><CardDescription>Try the supplied van image or any frame from Video Repertoire.</CardDescription></CardHeader><CardContent className="space-y-4"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed p-5"><Upload className="h-5 w-5" /><span className="text-sm">{file ? file.name : "Choose PNG, JPEG, WEBP, SVG or BMP"}</span><input className="hidden" type="file" accept="image/*,.svg" onChange={e => setFile(e.target.files?.[0] || null)} /></label><div className="flex flex-wrap items-end gap-4"><div><Label htmlFor="detail-mode">Analysis depth</Label><select id="detail-mode" className="mt-2 h-10 rounded-md border bg-background px-3" value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option value="quick">Quick</option><option value="balanced">Balanced</option><option value="deep">Deep</option></select></div><Button disabled={!file || busy} onClick={run}>{busy ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Analyzing…</> : <><ImageIcon className="mr-2 h-4 w-4" />Run detailer</>}</Button>{busy && runId ? <Button variant="outline" onClick={cancel}>Cancel</Button> : null}</div>{busy ? <div className="space-y-2"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${progress}%` }} /></div><p className="text-xs text-muted-foreground">{stage || "Preparing"} · {progress}%</p></div> : null}</CardContent></Card>
    {result && <div className="grid gap-6 lg:grid-cols-[0.8fr 1.2fr]"><Card><CardHeader><CardTitle>Input evidence</CardTitle><CardDescription>{result.input.filename} · {result.input.width}×{result.input.height}</CardDescription></CardHeader><CardContent><div className="space-y-2 text-sm"><p>Model: {result.model}</p><p>Mode: {result.mode}</p><p>Detected objects: {result.specialist_evidence?.detections?.length || 0}</p>{result.warnings?.map((w: string) => <p key={w} className="text-amber-600">{w}</p>)}</div><pre className="mt-4 max-h-64 overflow-auto rounded-lg bg-muted p-3 text-xs">{JSON.stringify(result.frame_card, null, 2)}</pre></CardContent></Card><Card><CardHeader><CardTitle>Structured analysis</CardTitle><CardDescription>Review this evidence before creating a generation brief.</CardDescription></CardHeader><CardContent><pre data-testid="image-detailer-result" className="max-h-[560px] overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(result.analysis, null, 2)}</pre></CardContent></Card></div>}</div></AppShell>;
}
