import { useEffect, useState } from "react";
import { Loader2, Music2, Play, Sparkles, Waves } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { CURRENT_PROJECT_KEY, createAceMusicJob, createControlFoleyJob, getControlFoleyCapabilities, getControlFoleyJob, getMusicCapabilities, getMusicJob, getProjectFileUrl, listProjects, type ControlFoleyCapabilities, type ControlFoleyJob, type MusicCapabilities, type MusicJob, type ProjectState } from "@/lib/project-api";

export default function MusicSound() {
  const [projects, setProjects] = useState<ProjectState[]>([]); const [projectId, setProjectId] = useState(localStorage.getItem(CURRENT_PROJECT_KEY) || "");
  const [caps, setCaps] = useState<MusicCapabilities | null>(null); const [mode, setMode] = useState("instrumental"); const [tags, setTags] = useState("cinematic, atmospheric, warm strings");
  const [lyrics, setLyrics] = useState("[Verse]\n\n[Chorus]\n"); const [duration, setDuration] = useState(30); const [seed, setSeed] = useState(1); const [advanced, setAdvanced] = useState(false);
  const [steps, setSteps] = useState(50); const [cfg, setCfg] = useState(5); const [job, setJob] = useState<MusicJob | null>(null); const [running, setRunning] = useState(false);
  const [foleyCaps,setFoleyCaps]=useState<ControlFoleyCapabilities|null>(null); const [foleyMode,setFoleyMode]=useState("text_audio"); const [foleyPrompt,setFoleyPrompt]=useState("Heavy footsteps on a wooden floor"); const [foleyVideo,setFoleyVideo]=useState<File|null>(null); const [foleyReference,setFoleyReference]=useState<File|null>(null); const [foleyDuration,setFoleyDuration]=useState(8); const [foleySeed,setFoleySeed]=useState(42); const [foleyJob,setFoleyJob]=useState<ControlFoleyJob|null>(null); const [foleyRunning,setFoleyRunning]=useState(false);
  useEffect(() => { Promise.all([listProjects(), getMusicCapabilities(), getControlFoleyCapabilities()]).then(([p, c, f]) => { setProjects(p); setCaps(c); setFoleyCaps(f); }); }, []);
  useEffect(() => { if (!job || !projectId || !["queued", "running"].includes(job.status)) return; const timer = window.setInterval(() => getMusicJob(projectId, job.job_id).then((next) => { setJob(next); if (!["queued", "running"].includes(next.status)) setRunning(false); }), 1800); return () => clearInterval(timer); }, [job, projectId]);
  useEffect(() => { if (!foleyJob || !projectId || !["queued", "running"].includes(foleyJob.status)) return; const timer = window.setInterval(() => getControlFoleyJob(projectId, foleyJob.job_id).then((next) => { setFoleyJob(next); if (!["queued", "running"].includes(next.status)) setFoleyRunning(false); }), 1800); return () => clearInterval(timer); }, [foleyJob, projectId]);
  const run = async () => { if (!projectId) return toast.error("Select a Story Builder project"); setRunning(true); try { setJob(await createAceMusicJob(projectId, { mode, tags, lyrics, duration, seed, steps, cfg })); } catch (error) { setRunning(false); toast.error(error instanceof Error ? error.message : "Could not queue music"); } };
  const runFoley=async()=>{if(!projectId)return toast.error("Select a Story Builder project");setFoleyRunning(true);try{setFoleyJob(await createControlFoleyJob(projectId,{mode:foleyMode,prompt:foleyPrompt,duration:foleyDuration,seed:foleySeed,steps:"fixed",guidance:4.5,fps:24},foleyVideo,foleyReference));}catch(error){setFoleyRunning(false);toast.error(error instanceof Error?error.message:"Could not queue Control-Foley");}};
  return <AppShell><div className="space-y-6"><div><Badge variant="outline">Generative music and Foley</Badge><h2 className="mt-3 text-3xl font-semibold">Music & Sound</h2><p className="text-muted-foreground">ACE-Step music creation, Control-Foley sound effects, and bounded ACE-Step fine-tuning preparation.</p></div>
    <Card className="rounded-3xl"><CardHeader><CardTitle>Project</CardTitle></CardHeader><CardContent><select className="h-10 w-full rounded-md border border-input bg-background px-3" value={projectId} onChange={(e) => { setProjectId(e.target.value); localStorage.setItem(CURRENT_PROJECT_KEY, e.target.value); }}><option value="">Select project</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select></CardContent></Card>
    <Card className="rounded-3xl border-primary/40"><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><Music2 className="h-5 w-5"/>ACE-Step Music Maker</CardTitle><Badge>{caps?.ace.status || "loading"}</Badge></div><CardDescription>Create an instrumental or structured-lyrics song through a fixed ComfyUI workflow.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><div><Label>Mode</Label><select className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3" value={mode} onChange={(e) => setMode(e.target.value)}><option value="instrumental">Instrumental</option><option value="song">Song</option></select></div><div><Label>Duration (seconds)</Label><Input className="mt-2" type="number" min={5} max={240} value={duration} onChange={(e) => setDuration(Number(e.target.value))}/></div><div><Label>Seed</Label><Input className="mt-2" type="number" value={seed} onChange={(e) => setSeed(Number(e.target.value))}/></div></div><div><Label>Music tags / prompt</Label><Textarea className="mt-2" value={tags} onChange={(e) => setTags(e.target.value)}/></div>{mode === "song" ? <div><Label>Structured lyrics</Label><Textarea className="mt-2 min-h-48" value={lyrics} onChange={(e) => setLyrics(e.target.value)}/></div> : null}<Button variant="outline" onClick={() => setAdvanced(!advanced)}>Advanced settings</Button>{advanced ? <div className="grid gap-4 md:grid-cols-2"><div><Label>Steps</Label><Input type="number" value={steps} onChange={(e) => setSteps(Number(e.target.value))}/></div><div><Label>CFG</Label><Input type="number" step="0.1" value={cfg} onChange={(e) => setCfg(Number(e.target.value))}/></div></div> : null}<div className="flex items-center gap-3"><Button onClick={run} disabled={running || caps?.ace.status !== "available"}>{running ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Play className="mr-2 h-4 w-4"/>}Generate music</Button>{job ? <Badge variant={job.status === "failed" ? "destructive" : "secondary"}>{job.status}</Badge> : null}</div>{job?.error ? <p className="text-sm text-destructive">{job.error}</p> : null}{job?.primary_output && projectId ? <audio className="w-full" controls src={getProjectFileUrl(projectId, job.primary_output.relative_path)}/> : null}</CardContent></Card>
    <Card className="rounded-3xl"><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><Waves className="h-5 w-5"/>Control-Foley Sound Effects</CardTitle><Badge variant={foleyCaps?.status==="available"?"default":"secondary"}>{foleyCaps?.status||"loading"}</Badge></div><CardDescription>Choose one fixed mode. Inputs enable only when the selected workflow requires them.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><div><Label>Mode</Label><select className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3" value={foleyMode} onChange={(e)=>{setFoleyMode(e.target.value);setFoleyVideo(null);setFoleyReference(null);}}>{foleyCaps?.schema.modes.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div><Label>Duration</Label><Input className="mt-2" type="number" min={.7} max={30} step={.5} value={foleyDuration} onChange={(e)=>setFoleyDuration(Number(e.target.value))}/></div><div><Label>Seed</Label><Input className="mt-2" type="number" min={0} value={foleySeed} onChange={(e)=>setFoleySeed(Number(e.target.value))}/></div></div>{foleyMode!=="reference_video_audio"?<div><Label>Sound description</Label><Textarea className="mt-2" value={foleyPrompt} onChange={(e)=>setFoleyPrompt(e.target.value)} placeholder="Describe the sound to generate"/></div>:null}{foleyMode!=="text_audio"?<div><Label>Video</Label><Input className="mt-2" type="file" accept="video/*" onChange={(e)=>setFoleyVideo(e.target.files?.[0]||null)}/></div>:null}{foleyMode==="reference_video_audio"?<div><Label>Reference audio</Label><Input className="mt-2" type="file" accept="audio/*" onChange={(e)=>setFoleyReference(e.target.files?.[0]||null)}/></div>:null}<div className="flex items-center gap-3"><Button onClick={runFoley} disabled={foleyRunning||foleyCaps?.status!=="available"||(foleyMode!=="reference_video_audio"&&!foleyPrompt.trim())||(foleyMode!=="text_audio"&&!foleyVideo)||(foleyMode==="reference_video_audio"&&!foleyReference)}>{foleyRunning?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Play className="mr-2 h-4 w-4"/>}Generate sound effect</Button>{foleyJob?<Badge variant={foleyJob.status==="failed"?"destructive":"secondary"}>{foleyJob.status}</Badge>:null}</div>{foleyJob?.error?<p className="text-sm text-destructive">{foleyJob.error}</p>:null}{foleyJob?.primary_output&&projectId?<audio className="w-full" controls src={getProjectFileUrl(projectId,foleyJob.primary_output.relative_path)}/>:null}</CardContent></Card>
    <Card className="rounded-3xl"><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5"/>ACE-Step Fine-tune</CardTitle><CardDescription>Dataset preparation and bounded smoke testing only; full training is disabled.</CardDescription></CardHeader><CardContent className="space-y-2">{caps?.finetune.checks.map((check) => <div key={check.name} className="flex justify-between rounded-xl border p-3 text-sm"><span>{check.name}</span><Badge variant={check.ok ? "default" : "destructive"}>{check.ok ? "ready" : "blocked"}</Badge></div>)}</CardContent></Card>
  </div></AppShell>;
}
