"""Durable project-scoped queue records for production image candidates.

This store deliberately does not talk to ComfyUI. It makes queued image work
restart-safe and auditable before a renderer is connected to the API.
Unknown submissions are never silently re-enqueued.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import sqlite3
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from story_builder.services.production_ledger import LedgerConflict, LedgerNotFound


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PATH = PROJECT_ROOT / "storage" / "production" / "v2_ledger.sqlite3"
TERMINAL = {"completed", "failed", "cancelled", "recovery_required"}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class ProductionImageJobStore:
    """SQLite queue metadata; generated bytes remain in the canonical output tree."""

    def __init__(self, path: str | Path | None = None) -> None:
        configured = os.environ.get("STORY_BUILDER_PRODUCTION_LEDGER_PATH")
        self.path = Path(path or configured or DEFAULT_PATH).expanduser().resolve()
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._initialize()

    def _connect(self) -> sqlite3.Connection:
        db = sqlite3.connect(self.path, timeout=30, isolation_level=None)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA busy_timeout=30000")
        return db

    def _initialize(self) -> None:
        with self._connect() as db:
            db.execute("""CREATE TABLE IF NOT EXISTS production_image_jobs (
                job_id TEXT PRIMARY KEY,
                batch_id TEXT NOT NULL,
                project_id TEXT NOT NULL,
                run_id TEXT NOT NULL,
                idempotency_key TEXT NOT NULL,
                candidate_index INTEGER NOT NULL,
                workflow_id TEXT NOT NULL,
                workflow_version TEXT NOT NULL,
                asset_role TEXT NOT NULL,
                prompt TEXT NOT NULL,
                seed INTEGER NOT NULL,
                settings_json TEXT NOT NULL,
                graph_json TEXT NOT NULL,
                status TEXT NOT NULL,
                prompt_id TEXT UNIQUE,
                output_asset_id TEXT,
                error_json TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE(project_id, idempotency_key, candidate_index)
            )""")
            db.execute("CREATE INDEX IF NOT EXISTS production_image_jobs_queue_idx ON production_image_jobs(status, created_at)")
            db.execute("CREATE INDEX IF NOT EXISTS production_image_jobs_batch_idx ON production_image_jobs(project_id, batch_id, candidate_index)")
            db.execute("""CREATE TABLE IF NOT EXISTS production_image_director_reviews (
                job_id TEXT PRIMARY KEY,
                project_id TEXT NOT NULL,
                run_id TEXT NOT NULL,
                asset_id TEXT NOT NULL,
                decision_json TEXT NOT NULL,
                resolution_status TEXT NOT NULL,
                retake_batch_id TEXT,
                error_json TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""")
            db.execute("""CREATE TABLE IF NOT EXISTS production_image_director_reassessments (
                job_id TEXT PRIMARY KEY,
                project_id TEXT NOT NULL,
                run_id TEXT NOT NULL,
                asset_id TEXT NOT NULL,
                decision_json TEXT NOT NULL,
                resolution_status TEXT NOT NULL,
                retake_batch_id TEXT,
                error_json TEXT,
                source_decision_hash TEXT NOT NULL,
                correction_reason TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )""")
            db.execute("""CREATE TABLE IF NOT EXISTS production_image_director_review_claims (
                job_id TEXT PRIMARY KEY,
                owner_token TEXT NOT NULL,
                lease_until TEXT NOT NULL,
                attempt_count INTEGER NOT NULL,
                updated_at TEXT NOT NULL
            )""")

    @staticmethod
    def _public(row: sqlite3.Row) -> dict[str, Any]:
        value = dict(row)
        for key in ("settings_json", "graph_json", "error_json"):
            raw = value.pop(key, None)
            if raw:
                value[key.removesuffix("_json")] = json.loads(raw)
        if isinstance(value.get("settings"), dict):
            value["settings"].pop("staging_owner_id", None)
        # Graphs may contain local staged filenames and are worker-private.
        value.pop("graph", None)
        return value

    def enqueue_batch(self, *, project_id: str, run_id: str, idempotency_key: str,
                      workflow_id: str, workflow_version: str, asset_role: str,
                      prompt: str, settings: dict[str, Any], candidates: list[dict[str, Any]]) -> dict[str, Any]:
        """Queue one batch, preserving the historical one-batch API."""
        return self.enqueue_batches([{
            "project_id": project_id, "run_id": run_id, "idempotency_key": idempotency_key,
            "workflow_id": workflow_id, "workflow_version": workflow_version,
            "asset_role": asset_role, "prompt": prompt, "settings": settings,
            "candidates": candidates,
        }])[0]

    def enqueue_batches(self, batches: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Persist several independently idempotent batches in one SQLite transaction.

        This is used when a controller admits a set of required identity masters:
        either every new batch is durable and renderable, or none of them is.
        Existing matching idempotency keys are returned unchanged.
        """
        if not batches:
            return []
        prepared = []
        for batch in batches:
            if not isinstance(batch, dict):
                raise ValueError("Each image batch request must be an object.")
            candidates = batch.get("candidates")
            if not isinstance(candidates, list) or not candidates or len(candidates) > 4:
                raise ValueError("Image candidate batch must contain 1–4 candidates.")
            if not all(isinstance(item, dict) and isinstance(item.get("graph"), dict)
                       and isinstance(item.get("seed"), int) and not isinstance(item.get("seed"), bool)
                       for item in candidates):
                raise ValueError("Each candidate must contain a compiled graph and integer seed.")
            required = ("project_id", "run_id", "idempotency_key", "workflow_id",
                        "workflow_version", "asset_role", "prompt")
            if any(not isinstance(batch.get(key), str) or not batch[key] for key in required):
                raise ValueError("Image batch identity and prompt fields must be non-empty strings.")
            settings = batch.get("settings")
            if not isinstance(settings, dict):
                raise ValueError("Image batch settings must be an object.")
            prepared.append({**batch,
                "settings_json": json.dumps(settings, sort_keys=True),
                "candidate_json": [(int(item["seed"]), json.dumps(item["graph"], sort_keys=True))
                                    for item in candidates]})

        now = _now()
        results = []
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            for batch in prepared:
                existing = db.execute("SELECT * FROM production_image_jobs "
                    "WHERE project_id=? AND idempotency_key=? ORDER BY candidate_index",
                    (batch["project_id"], batch["idempotency_key"])).fetchall()
                candidates = batch["candidates"]
                if existing:
                    # Idempotency means a retry returns the original batch, never another GPU job.
                    if (existing[0]["run_id"] != batch["run_id"]
                            or existing[0]["workflow_id"] != batch["workflow_id"]
                            or existing[0]["workflow_version"] != batch["workflow_version"]
                            or existing[0]["asset_role"] != batch["asset_role"]
                            or existing[0]["prompt"] != batch["prompt"]
                            or json.loads(existing[0]["settings_json"]) != batch["settings"]
                            or len(existing) != len(candidates)
                            or any(row["seed"] != candidate["seed"]
                                   or json.loads(row["graph_json"]) != candidate["graph"]
                                   for row, candidate in zip(existing, candidates))):
                        raise LedgerConflict("Image-job idempotency key was already used with different inputs.")
                    results.append({"batch_id": existing[0]["batch_id"],
                        "jobs": [self._public(row) for row in existing], "reused": True})
                    continue

                batch_id = str(uuid.uuid4())
                for index, (seed, graph_json) in enumerate(batch["candidate_json"], 1):
                    db.execute("""INSERT INTO production_image_jobs
                        (job_id,batch_id,project_id,run_id,idempotency_key,candidate_index,workflow_id,
                         workflow_version,asset_role,prompt,seed,settings_json,graph_json,status,created_at,updated_at)
                        VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                        (str(uuid.uuid4()), batch_id, batch["project_id"], batch["run_id"],
                         batch["idempotency_key"], index, batch["workflow_id"], batch["workflow_version"],
                         batch["asset_role"], batch["prompt"], seed, batch["settings_json"], graph_json,
                         "queued", now, now))
                rows = db.execute("SELECT * FROM production_image_jobs WHERE batch_id=? ORDER BY candidate_index",
                                  (batch_id,)).fetchall()
                results.append({"batch_id": batch_id, "jobs": [self._public(row) for row in rows],
                    "reused": False})
            db.commit()
        return results

    def list_batch(self, *, project_id: str, batch_id: str) -> dict[str, Any]:
        with self._connect() as db:
            jobs = self._batch_jobs(db, project_id, batch_id, depth=0)
        if not jobs:
            raise LedgerNotFound("Image candidate batch was not found.")
        settings = jobs[0].get("settings", {})
        director_review = settings.get("director_review_required") is True
        return {"batch_id": batch_id, "jobs": jobs,
            "generation_policy": {"initial_candidates": len(jobs),
                "selection_authority": "director" if director_review else "user",
                "retake_supported": director_review,
                "full_retake_budget": int(settings.get("full_retake_budget", 0))}}

    def _batch_jobs(self, db: sqlite3.Connection, project_id: str, batch_id: str,
                    *, depth: int) -> list[dict[str, Any]]:
        rows = db.execute("SELECT * FROM production_image_jobs WHERE project_id=? AND batch_id=? ORDER BY candidate_index",
                          (project_id, batch_id)).fetchall()
        jobs = [self._public(row) for row in rows]
        for job in jobs:
            review_row = db.execute("SELECT * FROM production_image_director_reviews WHERE project_id=? AND job_id=?",
                                    (project_id, job["job_id"])).fetchone()
            reassessed = db.execute("SELECT * FROM production_image_director_reassessments WHERE project_id=? AND job_id=?",
                                    (project_id, job["job_id"])).fetchone()
            review = self._review_public(reassessed or review_row)
            if reassessed:
                review["superseded_review"] = self._review_public(review_row)
            if review is None:
                claim = db.execute("SELECT lease_until,attempt_count FROM production_image_director_review_claims WHERE job_id=?",
                                   (job["job_id"],)).fetchone()
                if claim:
                    active = claim["lease_until"] > _now()
                    review = {"resolution_status": "reviewing" if active else "review_recovery_pending",
                        "attempt_count": int(claim["attempt_count"]), "lease_until": claim["lease_until"]}
            if review and review.get("retake_batch_id") and depth < 4:
                review["retake_jobs"] = self._batch_jobs(db, project_id,
                    str(review["retake_batch_id"]), depth=depth + 1)
            job["director_review"] = review
        return jobs

    def pending_director_review_jobs(self, *, limit: int = 20) -> list[dict[str, Any]]:
        """Return completed Full-mode candidates whose Director decision needs work."""
        with self._connect() as db:
            rows = db.execute("""SELECT j.* FROM production_image_jobs AS j
                LEFT JOIN production_image_director_reviews AS r ON r.job_id=j.job_id
                WHERE j.status='completed' AND j.output_asset_id IS NOT NULL
                AND r.job_id IS NULL
                ORDER BY j.created_at,j.candidate_index LIMIT ?""", (max(1, min(limit, 100)),)).fetchall()
        result = []
        for row in rows:
            job = dict(row)
            job["settings"] = json.loads(job.pop("settings_json"))
            job["graph"] = json.loads(job.pop("graph_json"))
            raw_error = job.pop("error_json", None)
            job["error"] = json.loads(raw_error) if raw_error else None
            if job["settings"].get("control_mode") == "fully_automated" or job["settings"].get("director_review_required") is True:
                result.append(job)
        return result

    def claim_next_director_review(self, *, owner_token: str, lease_seconds: int = 2400,
                                   max_attempts: int = 3) -> dict[str, Any] | None:
        """Atomically claim one completed Full-mode candidate for bounded review.

        A process restart may reclaim an expired lease. The long lease exceeds
        the review's bounded provider/admission timeouts, preventing concurrent
        backend instances from running duplicate inference for the same image.
        """
        if not owner_token or len(owner_token) > 200:
            raise ValueError("Director review owner token is invalid.")
        now = datetime.now(timezone.utc)
        now_text = now.isoformat()
        lease_until = (now + timedelta(seconds=max(60, min(lease_seconds, 7200)))).isoformat()
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            rows = db.execute("""SELECT j.*, c.owner_token AS claim_owner,
                    c.lease_until AS claim_lease_until, c.attempt_count AS claim_attempt_count
                FROM production_image_jobs AS j
                LEFT JOIN production_image_director_reviews AS r ON r.job_id=j.job_id
                LEFT JOIN production_image_director_review_claims AS c ON c.job_id=j.job_id
                WHERE j.status='completed' AND j.output_asset_id IS NOT NULL
                    AND r.job_id IS NULL AND (c.job_id IS NULL OR c.lease_until<=?)
                ORDER BY j.created_at,j.candidate_index""", (now_text,)).fetchall()
            for row in rows:
                settings = json.loads(row["settings_json"])
                if not (settings.get("control_mode") == "fully_automated"
                        or settings.get("director_review_required") is True):
                    continue
                attempts = int(row["claim_attempt_count"] or 0)
                job = dict(row)
                if attempts >= max(1, max_attempts):
                    job["settings"] = settings
                    job["graph"] = json.loads(job.pop("graph_json"))
                    job.pop("settings_json", None)
                    job.pop("error_json", None)
                    db.commit()
                    return {**job, "review_attempts_exhausted": True}
                next_attempt = attempts + 1
                db.execute("""INSERT INTO production_image_director_review_claims
                    (job_id,owner_token,lease_until,attempt_count,updated_at) VALUES(?,?,?,?,?)
                    ON CONFLICT(job_id) DO UPDATE SET owner_token=excluded.owner_token,
                    lease_until=excluded.lease_until,attempt_count=excluded.attempt_count,
                    updated_at=excluded.updated_at""",
                    (row["job_id"], owner_token, lease_until, next_attempt, now_text))
                job["settings"] = settings
                job["graph"] = json.loads(job.pop("graph_json"))
                job.pop("settings_json", None)
                job.pop("error_json", None)
                job["review_attempt_count"] = next_attempt
                db.commit()
                return job
            db.commit()
        return None

    def release_director_review_claim(self, *, job_id: str, owner_token: str) -> bool:
        with self._connect() as db:
            cursor = db.execute("UPDATE production_image_director_review_claims SET owner_token='',lease_until=?,updated_at=? WHERE job_id=? AND owner_token=?",
                                (_now(), _now(), job_id, owner_token))
            return cursor.rowcount == 1

    def record_director_review(self, *, project_id: str, run_id: str, job_id: str,
                               asset_id: str, decision: dict[str, Any],
                               owner_token: str | None = None) -> dict[str, Any]:
        """Persist one immutable Director decision before accepting or queueing a retake."""
        now = _now()
        encoded = json.dumps(decision, sort_keys=True)
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            job = db.execute("SELECT run_id,status,output_asset_id FROM production_image_jobs WHERE project_id=? AND job_id=?",
                             (project_id, job_id)).fetchone()
            if not job or job["run_id"] != run_id or job["status"] != "completed" or job["output_asset_id"] != asset_id:
                raise LedgerConflict("Director review does not match a completed candidate in this run.")
            if owner_token is not None:
                claim = db.execute("SELECT owner_token,lease_until FROM production_image_director_review_claims WHERE job_id=?",
                                   (job_id,)).fetchone()
                if (claim is None or claim["owner_token"] != owner_token
                        or claim["lease_until"] <= _now()):
                    raise LedgerConflict("Director review lease expired or belongs to another worker.")
            current = db.execute("SELECT * FROM production_image_director_reviews WHERE job_id=?", (job_id,)).fetchone()
            if current:
                if current["decision_json"] != encoded or current["asset_id"] != asset_id:
                    raise LedgerConflict("Director review for this candidate is immutable.")
                db.commit()
                return self._review_public(current)
            db.execute("""INSERT INTO production_image_director_reviews
                (job_id,project_id,run_id,asset_id,decision_json,resolution_status,created_at,updated_at)
                VALUES(?,?,?,?,?,'pending',?,?)""", (job_id, project_id, run_id, asset_id, encoded, now, now))
            row = db.execute("SELECT * FROM production_image_director_reviews WHERE job_id=?", (job_id,)).fetchone()
            db.commit()
        return self._review_public(row)

    @staticmethod
    def _review_public(row: sqlite3.Row | dict[str, Any] | None) -> dict[str, Any] | None:
        if row is None:
            return None
        value = dict(row)
        value["decision"] = json.loads(value.pop("decision_json"))
        raw_error = value.pop("error_json", None)
        value["error"] = json.loads(raw_error) if raw_error else None
        return value

    def record_director_reassessment(self, *, project_id: str, run_id: str, job_id: str,
                                    asset_id: str, source_decision_hash: str,
                                    correction_reason: str, decision: dict[str, Any],
                                    owner_token: str | None = None) -> dict[str, Any]:
        """One explicit evidence correction on the same bytes; never a new render budget.

        The original decision stays immutable. Only trusted Director acceptance
        may supersede a resolved rejection/hold; pending or retake chains cannot
        be redirected. The normal acceptance worker resolves the new record.
        """
        confidence = decision.get("confidence")
        criteria = decision.get("criteria")
        frame = decision.get("evidence")
        if (decision.get("action") != "accept" or not isinstance(confidence, (int, float))
                or isinstance(confidence, bool) or not math.isfinite(confidence)
                or not .75 <= confidence <= 1 or not isinstance(criteria, list) or not criteria
                or any(not isinstance(check, dict) or check.get("passed") is not True for check in criteria)
                or not isinstance(frame, dict) or frame.get("evidence_valid") is not True
                or not str(frame.get("summary") or "").strip()
                or not str(decision.get("reason") or "").strip()
                or not correction_reason.strip() or len(correction_reason) > 1200):
            raise ValueError("Evidence reassessment requires trusted Director acceptance and a correction reason.")
        encoded = json.dumps(decision, sort_keys=True)
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            job = db.execute("SELECT * FROM production_image_jobs WHERE project_id=? AND run_id=? AND job_id=?",
                             (project_id, run_id, job_id)).fetchone()
            original = db.execute("SELECT * FROM production_image_director_reviews WHERE project_id=? AND run_id=? AND job_id=?",
                                  (project_id, run_id, job_id)).fetchone()
            if not job or not original:
                raise LedgerNotFound("The candidate and original review must belong to this project/run.")
            if (job["status"] != "completed" or job["output_asset_id"] != asset_id
                    or original["asset_id"] != asset_id
                    or original["resolution_status"] not in {"rejected", "blocked"}):
                raise LedgerConflict("Only a completed held/rejected candidate can be reassessed.")
            if owner_token is not None:
                claim = db.execute("SELECT owner_token,lease_until FROM production_image_director_review_claims WHERE job_id=?",
                                   (job_id,)).fetchone()
                if (claim is None or claim["owner_token"] != owner_token
                        or claim["lease_until"] <= _now()):
                    raise LedgerConflict("Director reassessment lease expired or belongs to another worker.")
            original_decision = json.loads(original["decision_json"])
            expected_hash = hashlib.sha256(original["decision_json"].encode()).hexdigest()
            image_hash = original_decision.get("image_sha256")
            if (source_decision_hash != expected_hash or not isinstance(image_hash, str)
                    or len(image_hash) != 64 or decision.get("image_sha256") != image_hash
                    or decision.get("provider") != original_decision.get("provider")
                    or decision.get("director_profile_version") != original_decision.get("director_profile_version")):
                raise LedgerConflict("Reassessment must match the original decision, image bytes and pinned Director.")
            existing = db.execute("SELECT * FROM production_image_director_reassessments WHERE job_id=?", (job_id,)).fetchone()
            if existing:
                if (existing["decision_json"] != encoded or existing["source_decision_hash"] != source_decision_hash
                        or existing["correction_reason"] != correction_reason):
                    raise LedgerConflict("The one evidence reassessment is immutable.")
                db.commit()
                return self._review_public(existing)
            now = _now()
            db.execute("""INSERT INTO production_image_director_reassessments
                (job_id,project_id,run_id,asset_id,decision_json,resolution_status,source_decision_hash,correction_reason,created_at,updated_at)
                VALUES(?,?,?,?,?,'pending',?,?,?,?)""",
                (job_id, project_id, run_id, asset_id, encoded, source_decision_hash, correction_reason, now, now))
            row = db.execute("SELECT * FROM production_image_director_reassessments WHERE job_id=?", (job_id,)).fetchone()
            db.commit()
        return self._review_public(row)

    def claim_director_reassessment(self, *, project_id: str, job_id: str,
                                    owner_token: str, lease_seconds: int = 2400) -> bool:
        """Serialize the one evidence-only reassessment across worker processes."""
        if not owner_token or len(owner_token) > 200:
            raise ValueError("Director reassessment owner token is invalid.")
        now = datetime.now(timezone.utc)
        now_text = now.isoformat()
        lease_until = (now + timedelta(seconds=max(60, min(lease_seconds, 7200)))).isoformat()
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            job = db.execute("SELECT status,output_asset_id FROM production_image_jobs WHERE project_id=? AND job_id=?",
                             (project_id, job_id)).fetchone()
            review = db.execute("SELECT resolution_status FROM production_image_director_reviews WHERE project_id=? AND job_id=?",
                                (project_id, job_id)).fetchone()
            if (job is None or job["status"] != "completed" or not job["output_asset_id"]
                    or review is None or review["resolution_status"] not in {"rejected", "blocked"}):
                db.rollback()
                raise LedgerConflict("Only a completed held/rejected candidate can be claimed for reassessment.")
            current = db.execute("SELECT owner_token,lease_until,attempt_count FROM production_image_director_review_claims WHERE job_id=?",
                                 (job_id,)).fetchone()
            if current and current["owner_token"] and current["lease_until"] > now_text and current["owner_token"] != owner_token:
                db.rollback()
                return False
            attempts = (int(current["attempt_count"]) if current else 0) + 1
            db.execute("""INSERT INTO production_image_director_review_claims
                (job_id,owner_token,lease_until,attempt_count,updated_at) VALUES(?,?,?,?,?)
                ON CONFLICT(job_id) DO UPDATE SET owner_token=excluded.owner_token,
                lease_until=excluded.lease_until,attempt_count=excluded.attempt_count,updated_at=excluded.updated_at""",
                (job_id, owner_token, lease_until, attempts, now_text))
            db.commit()
        return True

    def get_director_review(self, *, project_id: str, job_id: str) -> dict[str, Any] | None:
        with self._connect() as db:
            row = db.execute("SELECT * FROM production_image_director_reviews WHERE project_id=? AND job_id=?",
                             (project_id, job_id)).fetchone()
            reassessed = db.execute("SELECT * FROM production_image_director_reassessments WHERE project_id=? AND job_id=?",
                                    (project_id, job_id)).fetchone()
        result = self._review_public(reassessed or row)
        if reassessed:
            result["superseded_review"] = self._review_public(row)
        return result

    def unresolved_director_reviews(self, *, limit: int = 20) -> list[dict[str, Any]]:
        with self._connect() as db:
            original = db.execute("SELECT * FROM production_image_director_reviews WHERE resolution_status='pending'").fetchall()
            corrections = db.execute("SELECT * FROM production_image_director_reassessments WHERE resolution_status='pending'").fetchall()
            rows = sorted([*original, *corrections], key=lambda row: row["created_at"])[:max(1, min(limit, 100))]
        return [self._review_public(row) for row in rows]

    def resolve_director_review(self, *, job_id: str, resolution_status: str,
                                retake_batch_id: str | None = None,
                                error: dict[str, Any] | None = None) -> dict[str, Any]:
        if resolution_status not in {"accepted", "retake_queued", "rejected", "blocked"}:
            raise ValueError("Invalid Director image review resolution status.")
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            corrected = db.execute("SELECT * FROM production_image_director_reassessments WHERE job_id=?", (job_id,)).fetchone()
            table = "production_image_director_reassessments" if corrected else "production_image_director_reviews"
            row = corrected or db.execute("SELECT * FROM production_image_director_reviews WHERE job_id=?", (job_id,)).fetchone()
            if row is None:
                raise LedgerNotFound("Director image review was not found.")
            if corrected and (resolution_status != "accepted" or retake_batch_id is not None):
                raise LedgerConflict("Evidence correction cannot enqueue a render or change the accepted decision.")
            current = str(row["resolution_status"])
            if current != "pending" and current != resolution_status:
                raise LedgerConflict("Director image review has already been resolved differently.")
            db.execute(f"UPDATE {table} SET resolution_status=?,retake_batch_id=COALESCE(?,retake_batch_id),error_json=?,updated_at=? WHERE job_id=?",
                       (resolution_status, retake_batch_id, json.dumps(error, sort_keys=True) if error else None, _now(), job_id))
            result = db.execute(f"SELECT * FROM {table} WHERE job_id=?", (job_id,)).fetchone()
            db.commit()
        return self._review_public(result)

    def get_job(self, *, project_id: str, job_id: str) -> dict[str, Any]:
        with self._connect() as db:
            row = db.execute("SELECT * FROM production_image_jobs WHERE project_id=? AND job_id=?", (project_id, job_id)).fetchone()
        if not row:
            raise LedgerNotFound("Image candidate job was not found in this project.")
        return self._public(row)

    def get_batch_by_idempotency_key(self, *, project_id: str, idempotency_key: str) -> dict[str, Any] | None:
        """Read the original durable request without recompiling it after a code update."""
        with self._connect() as db:
            row = db.execute("SELECT batch_id FROM production_image_jobs WHERE project_id=? AND idempotency_key=? ORDER BY candidate_index LIMIT 1",
                             (project_id, idempotency_key)).fetchone()
        return self.list_batch(project_id=project_id, batch_id=row["batch_id"]) if row else None

    def has_idempotency_key(self, *, project_id: str, idempotency_key: str) -> bool:
        with self._connect() as db:
            row = db.execute("SELECT 1 FROM production_image_jobs WHERE project_id=? AND idempotency_key=? LIMIT 1",
                             (project_id, idempotency_key)).fetchone()
        return row is not None

    def existing_source_asset_ids(self, *, project_id: str, idempotency_key: str) -> list[str] | None:
        with self._connect() as db:
            row = db.execute("SELECT settings_json FROM production_image_jobs WHERE project_id=? AND idempotency_key=? ORDER BY candidate_index LIMIT 1",
                             (project_id, idempotency_key)).fetchone()
        if row is None:
            return None
        value = json.loads(row["settings_json"])
        sources = value.get("source_asset_ids", [])
        return sources if isinstance(sources, list) else None

    def batch_is_settled(self, *, project_id: str, batch_id: str) -> bool:
        """Only report settled when every candidate has a known terminal outcome."""
        with self._connect() as db:
            rows = db.execute("SELECT status FROM production_image_jobs WHERE project_id=? AND batch_id=?",
                              (project_id, batch_id)).fetchall()
        return bool(rows) and all(row["status"] in {"completed", "failed", "cancelled"} for row in rows)

    def recovery_jobs(self, *, limit: int = 20) -> list[dict[str, Any]]:
        """Return worker-private details for submitted jobs awaiting reconciliation."""
        with self._connect() as db:
            rows = db.execute("""SELECT * FROM production_image_jobs
                WHERE status='recovery_required' AND prompt_id IS NOT NULL
                ORDER BY updated_at LIMIT ?""", (max(1, min(limit, 100)),)).fetchall()
        jobs = []
        for row in rows:
            item = dict(row)
            item["settings"] = json.loads(item.pop("settings_json"))
            item["graph"] = json.loads(item.pop("graph_json"))
            raw_error = item.pop("error_json", None)
            item["error"] = json.loads(raw_error) if raw_error else None
            jobs.append(item)
        return jobs

    def next_queued(self) -> dict[str, Any] | None:
        """Claim one backend job. The caller serializes GPU submission globally."""
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT * FROM production_image_jobs WHERE status='queued' ORDER BY created_at,candidate_index LIMIT 1").fetchone()
            if row is None:
                db.commit()
                return None
            now = _now()
            db.execute("UPDATE production_image_jobs SET status='preparing',updated_at=? WHERE job_id=? AND status='queued'", (now, row["job_id"]))
            claimed = db.execute("SELECT * FROM production_image_jobs WHERE job_id=?", (row["job_id"],)).fetchone()
            db.commit()
        result = dict(claimed)
        result["settings"] = json.loads(result.pop("settings_json"))
        result["graph"] = json.loads(result.pop("graph_json"))
        result.pop("error_json", None)
        return result

    def transition(self, job_id: str, status: str, *, prompt_id: str | None = None,
                   output_asset_id: str | None = None, error: dict[str, Any] | None = None) -> dict[str, Any]:
        allowed = {"preparing": {"queued", "submitting", "failed", "cancelled"},
                   "submitting": {"running", "failed", "recovery_required"},
                   "running": {"completed", "failed", "recovery_required"},
                   "recovery_required": {"running", "failed", "completed"},
                   "queued": {"cancelled"}}
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT * FROM production_image_jobs WHERE job_id=?", (job_id,)).fetchone()
            if row is None:
                raise LedgerNotFound("Image candidate job was not found.")
            current = str(row["status"])
            if status not in allowed.get(current, set()):
                if current == status:
                    db.commit()
                    return self._public(row)
                raise LedgerConflict(f"Image candidate cannot transition from {current} to {status}.")
            if status == "running" and (prompt_id or row["prompt_id"]) is None:
                raise LedgerConflict("Persist the ComfyUI prompt ID before marking an image job running.")
            db.execute("UPDATE production_image_jobs SET status=?,prompt_id=COALESCE(?,prompt_id),output_asset_id=COALESCE(?,output_asset_id),error_json=?,updated_at=? WHERE job_id=?",
                       (status, prompt_id, output_asset_id,
                        json.dumps(error, sort_keys=True) if error else None, _now(), job_id))
            updated = db.execute("SELECT * FROM production_image_jobs WHERE job_id=?", (job_id,)).fetchone()
            db.commit()
        return self._public(updated)

    def reserve_prompt_id(self, job_id: str) -> str:
        prompt_id = str(uuid.uuid4())
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT status,prompt_id FROM production_image_jobs WHERE job_id=?", (job_id,)).fetchone()
            if row is None:
                raise LedgerNotFound("Image candidate job was not found.")
            if row["status"] != "preparing" or row["prompt_id"]:
                raise LedgerConflict("A prompt ID can only be reserved once, immediately before submission.")
            db.execute("UPDATE production_image_jobs SET status='submitting',prompt_id=?,updated_at=? WHERE job_id=?", (prompt_id, _now(), job_id))
            db.commit()
        return prompt_id

    def mark_orphaned_submissions_for_recovery(self) -> int:
        """Fail safe on restart: known prompt IDs need reconciliation, never resubmission."""
        with self._connect() as db:
            cursor = db.execute("UPDATE production_image_jobs SET status='recovery_required',error_json=?,updated_at=? WHERE status IN ('submitting','running')",
                                (json.dumps({"code": "worker_restarted", "message": "Reconcile the recorded ComfyUI prompt before retrying; no automatic resubmission was made."}), _now()))
            return int(cursor.rowcount)

    def reconcile_after_restart(self) -> dict[str, int]:
        """Recover only work whose remote submission is provably not started.

        A job in ``preparing`` has no reserved prompt ID and therefore cannot
        have been submitted by this worker; return it to the website queue.
        Once a prompt ID is reserved, the outcome may be remote/unknown, so
        hold it for explicit reconciliation instead of creating duplicate GPU
        work. Keep both updates in one SQLite transaction.
        """
        now = _now()
        safe_error = json.dumps({"code": "worker_restarted_before_submit",
            "message": "Worker restarted before reserving a ComfyUI prompt ID; safely returned to the website queue."})
        unknown_error = json.dumps({"code": "worker_restarted",
            "message": "Reconcile the recorded ComfyUI prompt before retrying; no automatic resubmission was made."})
        with self._connect() as db:
            db.execute("BEGIN IMMEDIATE")
            preparing = db.execute("UPDATE production_image_jobs SET status='queued',error_json=?,updated_at=? WHERE status='preparing' AND prompt_id IS NULL",
                                   (safe_error, now)).rowcount
            unknown = db.execute("UPDATE production_image_jobs SET status='recovery_required',error_json=?,updated_at=? WHERE status IN ('submitting','running')",
                                 (unknown_error, now)).rowcount
            # A preparing row that already has a prompt ID is inconsistent but
            # cannot safely be resent. Protect it with the same recovery gate.
            inconsistent = db.execute("UPDATE production_image_jobs SET status='recovery_required',error_json=?,updated_at=? WHERE status='preparing' AND prompt_id IS NOT NULL",
                                      (unknown_error, now)).rowcount
            db.commit()
        return {"requeued_unsubmitted": int(preparing),
                "held_for_reconciliation": int(unknown + inconsistent)}
