"""Project-scoped preparation and output collection for durable H3 takes.

This module never trusts client filesystem paths. Callers supply the existing
project/repertoire ID resolvers and the exact validation function used by the
preview endpoint. Staging is take/attempt-owned; generated bytes have one
durable owner under output/<project_id>/production_v2/.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Callable, Mapping

from story_builder.services import minimax_h3_media
from story_builder.services.minimax_h3_graph_compiler import (
    AudioReference, ImageReference, ReferencePlan, ResolvedAsset, VideoReference,
    compile_r2v_graph,
)
from story_builder.services.minimax_h3_t2v import compile_t2v_graph
from story_builder.services.production_job_worker import PreparedTake
from story_builder.services.production_assets import register_output, get_asset_record
from story_builder.services.media_jobs import collect_outputs


LOGGER = logging.getLogger(__name__)
SAFE_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,120}$")


def _plan_from_dict(value: Mapping[str, Any]) -> ReferencePlan:
    return ReferencePlan(
        schema_version=int(value["schema_version"]), project_id=str(value["project_id"]),
        run_id=str(value["run_id"]), shot_id=str(value["shot_id"]), prompt=str(value["prompt"]),
        duration_seconds=float(value["duration_seconds"]), resolution_preset=float(value.get("resolution_preset", .98)),
        aspect_ratio=str(value.get("aspect_ratio", "16:9")), steps=int(value.get("steps", 20)),
        ref_image_size=str(value.get("ref_image_size", "match")), seed=int(value.get("seed", 1)),
        images=tuple(ImageReference(**row) for row in value.get("images", [])),
        videos=tuple(VideoReference(**row) for row in value.get("videos", [])),
        standalone_audios=tuple(AudioReference(**row) for row in value.get("standalone_audios", [])),
    )


def make_take_preparer(*, validate: Callable[[dict[str, Any]], dict[str, Any]],
                       resolve_source: Callable[[str, str], Path],
                       comfy_input_dir: Path, owner_root: Path,
                       ffmpeg: str = "ffmpeg", ffprobe: str = "ffprobe") -> Callable[[dict[str, Any]], PreparedTake]:
    """Build the worker's prepare callback from owner-scoped application APIs."""
    def prepare(take: dict[str, Any]) -> PreparedTake:
        snapshot = take.get("input_snapshot") or {}
        validation_payload = snapshot.get("validation_request")
        expected_validation_hash = snapshot.get("validation_hash")
        if not isinstance(validation_payload, dict) or not isinstance(expected_validation_hash, str):
            raise ValueError("take_snapshot_invalid: saved request/hash are missing")
        check = validate(take, validation_payload)
        if not check.get("valid") or check.get("validation_hash") != expected_validation_hash:
            raise ValueError("shot_validation_stale: inputs or plan changed since the user validated this take")
        readiness = check.get("workflow_readiness", {})
        if not readiness.get("available"):
            raise ValueError("h3_workflow_unavailable: exact H3 capability is no longer ready")
        plan = _plan_from_dict(check["plan"])
        owner_id = f"{take['take_id']}_a{int(take.get('attempt') or 1)}"
        if not SAFE_ID.fullmatch(owner_id):
            raise ValueError("unsafe_take_id: cannot create a staging owner for this take")
        index: dict[str, ResolvedAsset] = {}
        try:
            if check.get("workflow_id") == "minimax_h3_t2v_local_v1":
                compiled_t2v = compile_t2v_graph(plan)
                LOGGER.info("Prepared production H3 T2V take project=%s run=%s shot=%s take=%s attempt=%s validation=%s graph_nodes=%d",
                    plan.project_id, plan.run_id, plan.shot_id, take["take_id"], take.get("attempt"),
                    expected_validation_hash[:16], len(compiled_t2v["graph"]))
                return PreparedTake(dict(compiled_t2v["graph"]), lambda: None)
            for ref in plan.images:
                source = resolve_source(plan.project_id, ref.asset_id)
                staged = minimax_h3_media.stage_image_reference(source, asset_id=ref.asset_id,
                    owner_id=owner_id, comfy_input_dir=comfy_input_dir, owner_root=owner_root,
                    ffprobe=ffprobe)
                index[ref.asset_id] = ResolvedAsset(ref.asset_id, "image", staged.filename, staged.sha256)
            for ref in plan.videos:
                source = resolve_source(plan.project_id, ref.asset_id)
                staged = minimax_h3_media.stage_video_reference(source, asset_id=ref.asset_id,
                    owner_id=owner_id, comfy_input_dir=comfy_input_dir, owner_root=owner_root,
                    start_sec=ref.start_sec, end_sec=ref.end_sec,
                    include_audio=ref.include_paired_soundtrack, ffmpeg=ffmpeg, ffprobe=ffprobe)
                index[ref.asset_id] = ResolvedAsset(ref.asset_id, "video", staged.filename,
                    staged.sha256, staged.source_start_sec, staged.source_end_sec, staged.has_audio)
            for ref in plan.standalone_audios:
                source = resolve_source(plan.project_id, ref.asset_id)
                staged = minimax_h3_media.stage_audio_reference(source, asset_id=ref.asset_id,
                    owner_id=owner_id, comfy_input_dir=comfy_input_dir, owner_root=owner_root,
                    ffmpeg=ffmpeg, ffprobe=ffprobe)
                index[ref.asset_id] = ResolvedAsset(ref.asset_id, "audio", staged.filename, staged.sha256)
            compiled = compile_r2v_graph(plan, index)
            LOGGER.info("Prepared production H3 take project=%s run=%s shot=%s take=%s attempt=%s assets=%d validation=%s graph_nodes=%d",
                plan.project_id, plan.run_id, plan.shot_id, take["take_id"], take.get("attempt"),
                len(index), expected_validation_hash[:16], len(compiled.graph))
            return PreparedTake(dict(compiled.graph), lambda: minimax_h3_media.cleanup_owned_media(
                owner_id, comfy_input_dir=comfy_input_dir, owner_root=owner_root))
        except Exception:
            minimax_h3_media.cleanup_owned_media(owner_id, comfy_input_dir=comfy_input_dir, owner_root=owner_root)
            raise
    return prepare


def make_output_collector(*, output_root: Path,
                          storage_projects_root: Path,
                          comfy_url: str,
                          download_outputs: Callable[..., list[dict[str, Any]]] = collect_outputs) -> Callable[[dict[str, Any], dict[str, Any]], list[dict[str, Any]]]:
    """Copy Comfy results once into the project's durable output tree and index them."""
    def collect(take: dict[str, Any], history_state: dict[str, Any]) -> list[dict[str, Any]]:
        project_id, run_id, shot_id, take_id = (str(take[key]) for key in ("project_id", "run_id", "shot_id", "take_id"))
        if not all(SAFE_ID.fullmatch(value) for value in (project_id, run_id, shot_id, take_id)):
            raise ValueError("unsafe_output_identity: project/run/shot/take identifiers are invalid")
        project_output = (Path(output_root).resolve() / project_id).resolve()
        attempt = max(1, int(take.get("attempt") or 1))
        relative_dir = Path("production_v2") / "runs" / run_id / "shots" / shot_id / "takes" / take_id / f"attempt-{attempt}"
        destination = (project_output / relative_dir).resolve()
        if not destination.is_relative_to(project_output):
            raise ValueError("unsafe_output_path: take destination escapes project output")
        copied = download_outputs(history_state, destination_dir=destination, comfy_url=comfy_url)
        indexed: list[dict[str, Any]] = []
        has_video = False
        try:
            for row in copied:
                kind = str(row.get("kind"))
                if kind not in {"video", "audio", "image"}:
                    continue
                path = (destination / str(row.get("relative_path", ""))).resolve()
                if not path.is_relative_to(destination) or not path.is_file():
                    continue
                if kind == "video":
                    if path.suffix.lower() not in {".mp4", ".mov", ".mkv", ".webm"}:
                        LOGGER.warning("Ignoring unsupported generated video suffix take=%s filename=%s", take_id, path.name)
                        continue
                    role = "project_video"
                    has_video = True
                elif kind == "audio":
                    role = "h3_native_audio"
                else:
                    role = "project_image"
                record = register_output(storage_projects_root, output_root, project_id,
                    relative_path=path.relative_to(project_output).as_posix(), role=role,
                    metadata={"origin": "production_v2_h3", "approval_status": "candidate",
                        "run_id": run_id, "shot_id": shot_id, "take_id": take_id,
                        "attempt": attempt, "review_required": True})
                if kind == "video":
                    # This role only makes the bytes eligible for explicit
                    # same-scene continuity selection. The controller still
                    # requires an accepted ledger take and verifies the exact
                    # run/shot/take provenance before exposing it.
                    register_output(storage_projects_root, output_root, project_id,
                        relative_path=path.relative_to(project_output).as_posix(),
                        role="previous_cut_tail",
                        metadata={"origin": "production_v2_h3", "approval_status": "candidate",
                            "run_id": run_id, "shot_id": shot_id, "take_id": take_id,
                            "attempt": attempt, "review_required": True})
                private = get_asset_record(storage_projects_root, project_id, record["asset_id"])
                if record.get("deduplicated") and private["relative_path"] != path.relative_to(project_output).as_posix():
                    # The bytes already have one durable project owner. Remove
                    # this newly downloaded duplicate, retaining the canonical file.
                    path.unlink(missing_ok=True)
                indexed.append({"asset_id": record["asset_id"], "kind": kind,
                    "sha256": record["sha256"], "relative_path": private["relative_path"],
                    "filename": record["filename"], "approval_status": "candidate"})
            if not has_video:
                raise ValueError("output_missing_video: ComfyUI completed without a playable video output")
            return indexed
        except Exception:
            # Keep successful/partial output bytes for diagnosis, but they are
            # deliberately not accepted or listed as a successful take.
            LOGGER.exception("Production H3 output indexing failed take=%s; output remains in its attempt folder for recovery", take_id)
            raise
    return collect
